### ISSUE TITLE
Different SMPL shape.

### ISSUE THREAD

**Issue by interestingzhuo** [ZhengyiLuo/PerpetualHumanoidControl#12]
It seems that you don’t have a random sampling sequence when implementing different shapes. It seems that you load the corresponding skeleton_tree into the simulator in advance, and then each env always corresponds to the same skeleton.
I saw that there is logic in the code to destroy sim and then recreate the environment, but it was commented out. Why is it useless later?

**Comment by ZhengyiLuo** [comment]
Two reasons: 

- There are only ~500 unique body shapes from AMASS, so tiling them sequentially in e.g. 3072 environment makes sure that you are sampling all the shapes. 
- Some body shape from AMASS will trigger an IsaacGym bug where the humanoid will move uncontrollably. You can try this by using the `amass_isaac_gender_betas.pkl` instead of `amass_isaac_gender_betas_unique.pkl`, there will be a number of body shapes that have issues. The `amass_isaac_gender_betas_unique.pkl` file is after filtering those out. Due to the same issue, I do not sample random body shapes, since it would trigger the same issue. I find that destroying sim and resampling unnecessary as a result. 

https://github.com/ZhengyiLuo/PerpetualHumanoidControl/assets/13114740/9a2432cc-3e11-477f-adb6-c8f5325bb7d6
